[package]
name = "embedded-recruitment-task"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.4"
log = "0.4"
env_logger = "0.11.6"

[build-dependencies]
prost-build = "0.13.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
 